"""NewOne

Revision ID: dc1848c8a75e
Revises: 46d987bec40f
Create Date: 2024-01-23 00:43:13.290770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc1848c8a75e'
down_revision: Union[str, None] = '46d987bec40f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_tb',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_tb',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('refresh', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('expire_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_tb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_tb_id'), 'token_tb', ['id'], unique=False)
    op.create_index(op.f('ix_token_tb_refresh'), 'token_tb', ['refresh'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_tb_refresh'), table_name='token_tb')
    op.drop_index(op.f('ix_token_tb_id'), table_name='token_tb')
    op.drop_table('token_tb')
    op.drop_table('users_tb')
    # ### end Alembic commands ###
